Online-Shop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Online_Shop.Models;
using Online_Shop.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Online_Shop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private TomasosContext _context;

        public AdminController(TomasosContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult ManageMenu()
        {
            var model = GetViewModel();

            return View(model);
        }

        public IActionResult EditMenu(int id)
        {
            var model = GetViewModel();

            model.CurrentFood = model.AllFoods.SingleOrDefault(f => f.FoodId == id);

            return View(model);
        }


        [HttpPost]
        public IActionResult EditMenu(ViewModelFood edited)
        {
            var old = GetViewModel();

            old.CurrentFood = _context.Food.SingleOrDefault(f => f.FoodId == edited.CurrentFood.FoodId);
            edited.CurrentFood.Ingredients = new List<Ingredient>();

            foreach (var item in edited.AllIngredients)
            {
                if (item.Selected == true)
                {
                    if (old.CurrentFood.Ingredients.FirstOrDefault(i => i.IngredientId == item.IngredientId) == null)
                    {
                        FoodIngredient foodIng = new FoodIngredient();
                        foodIng.FoodId = edited.CurrentFood.FoodId;
                        foodIng.IngredientId = item.IngredientId;

                        _context.Add(foodIng);
                        _context.SaveChanges();
                    }

                }
                else
                {
                    if (old.CurrentFood.Ingredients.FirstOrDefault(i => i.IngredientId == item.IngredientId) != null)
                    {
                        var foodIng = _context.FoodIngredient.FirstOrDefault(i => i.IngredientId == item.IngredientId
                                     && i.FoodId == edited.CurrentFood.FoodId);

                        _context.Remove(foodIng);
                        _context.SaveChanges();
                    }
                }
            }
    

                _context.Entry(old.CurrentFood).CurrentValues.SetValues(edited.CurrentFood);
            _context.SaveChanges();

            return RedirectToAction("ManageMenu");
        }

        public IActionResult AddFood()
        {
            var model = GetViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult AddFood(ViewModelFood model)
        {
            Food food = new Food();
            food.Name = model.CurrentFood.Name;
            food.CategoryId = model.CurrentFood.CategoryId;
            food.Price = model.CurrentFood.Price;

            _context.Food.Add(food);
            _context.SaveChanges();

            foreach (var item in model.AllIngredients)
            {
                if (item.Selected == true)
                {
                        FoodIngredient foodIng = new FoodIngredient();
                        foodIng.FoodId = model.CurrentFood.FoodId;
                        foodIng.IngredientId = item.IngredientId;

                        _context.Add(foodIng);
                        _context.SaveChanges();
                }
            }

            return RedirectToAction("ManageMenu");
        }

        public IActionResult ManageIngredients()
        {
            var model = GetViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult ManageIngredients(ViewModelFood model)
        {
            Ingredient ing = new Ingredient();
            ing.IngredientName = model.CurrentIngredient.IngredientName;

            _context.Ingredient.Add(ing);
            _context.SaveChanges();

            return RedirectToAction("ManageIngredients");
        }

        public IActionResult RemoveIngredient(int id)
        {
            var ing = _context.Ingredient.SingleOrDefault(i => i.IngredientId == id);

            _context.Remove(ing);
            _context.SaveChanges();

            return RedirectToAction("ManageIngredients");
        }

        [HttpPost]
        public IActionResult EditIngredient(ViewModelFood edited)
        {
            var old = GetViewModel();
            old.CurrentIngredient = _context.Ingredient.SingleOrDefault(i => i.IngredientId == edited.CurrentIngredient.IngredientId);

            _context.Entry(old.CurrentIngredient).CurrentValues.SetValues(edited.CurrentIngredient);
            _context.SaveChanges();

            return RedirectToAction("ManageIngredients");
        }

        public IActionResult ManageOrders()
        {
            var model = GetViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult ChangeOrderState(ViewModelFood model)
        {
            var order = _context.Order.SingleOrDefault(o => o.OrderId == model.CurrentOrder.OrderId);

            _context.Entry(order).CurrentValues.SetValues(model.CurrentOrder);
            _context.SaveChanges();

            return RedirectToAction("ManageOrders");
        }

        public IActionResult RemoveOrder(int id)
        {
            var foodOrders = _context.FoodOrder.Where(f => f.OrderId == id).ToList();

            foreach(var item in foodOrders)
            {
                _context.Remove(item);
                _context.SaveChanges();
            }

            var order = _context.Order.SingleOrDefault(o => o.OrderId == id);

            _context.Remove(order);
            _context.SaveChanges();

            return RedirectToAction("ManageOrders");
        }

        public IActionResult ManageUsers()
        {
            var model = GetViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult ChangeMembership(ViewModelFood model)
        {
            if (model.CurrentUser.isPremium)
            {
                AspNetUserRoles role = new AspNetUserRoles();
                role.RoleId = ("F4F4367D-940C-4FD7-A848-137508F418C1");
                role.UserId = model.CurrentUser.Id;

                var cust = _context.Customer.SingleOrDefault(c => c.UserId == role.UserId);
                cust.Points = 0;

                _context.AspNetUserRoles.Add(role);
                _context.SaveChanges();
            }
            else
            {
                var role = _context.AspNetUserRoles.SingleOrDefault(r => r.UserId == model.CurrentUser.Id && 
                                                            r.RoleId == "F4F4367D-940C-4FD7-A848-137508F418C1");

                var cust = _context.Customer.SingleOrDefault(c => c.UserId == role.UserId);
                cust.Points = 0;

                _context.Remove(role);
                _context.SaveChanges();
            }

            return RedirectToAction("ManageUsers");
        }

        public IActionResult ChangeAdmin(ViewModelFood model)
        {
            if (model.CurrentUser.isAdmin)
            {
                AspNetUserRoles role = new AspNetUserRoles();
                role.RoleId = ("1F6CE05B-A599-4985-9AB0-87A5BBAE970A");
                role.UserId = model.CurrentUser.Id;

                _context.AspNetUserRoles.Add(role);
                _context.SaveChanges();
            }
            else
            {
                var role = _context.AspNetUserRoles.SingleOrDefault(r => r.UserId == model.CurrentUser.Id &&
                                                            r.RoleId == "1F6CE05B-A599-4985-9AB0-87A5BBAE970A");
                _context.Remove(role);
                _context.SaveChanges();
            }

            return RedirectToAction("ManageUsers");
        }

        public ViewModelFood GetViewModel()
        {
            ViewModelFood model = new ViewModelFood();
            model.AllFoods = _context.Food.ToList();
            model.AllFoodIngredients = _context.FoodIngredient.ToList();
            model.AllIngredients = _context.Ingredient.OrderBy(i => i.IngredientName).ToList();
            model.AllFoodOrders = _context.FoodOrder.ToList();
            model.AllOrders = _context.Order.ToList();
            model.AllUsers = _context.AspNetUsers.ToList();

            foreach (var item in _context.Category)
            {
                model.AllCategories.Add(new SelectListItem { Text = item.Title, Value = item.CategoryId.ToString() });
                
            }

            foreach (var item in model.AllFoods)
            {
                foreach (var ing in model.AllFoodIngredients.Where(f => f.FoodId == item.FoodId).ToList())
                {
                    item.Ingredients.Add(model.AllIngredients.SingleOrDefault(i => i.IngredientId == ing.IngredientId));
                }
            }

            foreach (var item in model.AllOrders)
            {
                item.Customer = _context.Customer.SingleOrDefault(c => c.CustomerId == item.CustomerId);
            }

            foreach (var item in model.AllUsers)
            {
                var roles = _context.AspNetUserRoles.Where(r => r.UserId == item.Id);

                foreach (var role in roles)
                {
                    var userRole = _context.AspNetRoles.Where(ur => ur.Id == role.RoleId).ToList();

                    foreach (var ur in userRole)
                    {
                        if (ur.NormalizedName == "PREMIUM")
                        {
                            item.isPremium = true;
                        }

Online-Shop/Views/Admin/AddFood.cshtml

@model Online_Shop.ViewModels.ViewModelFood

<h1>Edit menu</h1>
<hr class="accent my-5">

<form asp-controller="Admin" asp-action="AddFood" method="post">
    <div class="form-group">
        <label asp-for="CurrentFood.Name">Name</label>
        <input type="text" asp-for="CurrentFood.Name" class="form-control" id="inputName4" placeholder="Name">
        <span asp-validation-for="CurrentFood.Name" style="color: red;"></span>
    </div>
    <div class="form-group">
        <label asp-for="CurrentFood.Price"></label>
        <input type="number" asp-for="CurrentFood.Price" class="form-control" id="inputPrice4" placeholder="Price">
        <span asp-validation-for="CurrentFood.Price" style="color: red;"></span>
    </div>
    <div class="form-group">
        <label asp-for="CurrentFood.Category"></label>
        <select asp-for="@Model.CurrentFood.CategoryId"
                asp-items="Model.AllCategories"></select>
        <span asp-validation-for="CurrentFood.Category" style="color: red;"></span>
    </div>

    @*<div id="ingredient-list-check" class="form-check">
        <ul>
            @foreach (var item in Model.AllIngredients)
            {
                <li>
                    <input class="form-check-input" asp-for="@item.Selected" type="checkbox" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">@item.IngredientName</label>
                    <input asp-for="@item.IngredientId" type="hidden" />
                    <input asp-for="@item.IngredientName" type="hidden" />
                </li>
            }
        </ul>
    </div>*@

    @*/ TODO - FIX INGREDIENTS '*@

    <button type="submit" class="btn btn-primary">Save</button>
</form>

<a asp-controller="Admin" asp-action="ManageIngredients">Manage ingredients</a>
@*<a asp-controller="Admin" asp-action="DeleteFood" asp-route-id="@Model.CurrentFood.FoodId">Delete</a>*@

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

Online-Shop/Views/Admin/EditMenu.cshtml
@model Online_Shop.ViewModels.ViewModelFood

<h1>Edit menu</h1>

<form asp-controller="Admin" asp-action="EditMenu" method="post">
    <input type="hidden" asp-for="@Model.CurrentFood.FoodId" value="@Model.CurrentFood.FoodId" />
    <div class="form-group">
        <label asp-for="CurrentFood.Name">Name</label>
        <input type="text" asp-for="CurrentFood.Name" class="form-control" id="inputName4" placeholder="Name">
        <span asp-validation-for="CurrentFood.Name" style="color: red;"></span>
    </div>
    <div class="form-group">
        <label asp-for="CurrentFood.Price"></label>
        <input type="number" asp-for="CurrentFood.Price" class="form-control" id="inputPrice4" placeholder="Price">
        <span asp-validation-for="CurrentFood.Price" style="color: red;"></span>
    </div>
    <div class="form-group">
        <label asp-for="CurrentFood.Category"></label>
        <select asp-for="@Model.CurrentFood.CategoryId" value="@Model.CurrentFood.CategoryId"
                asp-items="Model.AllCategories"></select>
        <span asp-validation-for="CurrentFood.Category" style="color: red;"></span>
    </div>

    <div id="ingredient-list-check" class="form-check">
        <ul>
            @for (int i = 0; i < Model.AllIngredients.Count; i++)
            {
                <li>
                    @if (Model.CurrentFood.Ingredients.Contains(Model.AllIngredients[i]))
                    {
                        <input class="form-check-input" asp-for="@Model.AllIngredients[i].Selected" type="checkbox" id="defaultCheck1" checked>
                        <label class="form-check-label" for="defaultCheck1">@Model.AllIngredients[i].IngredientName</label>
                        <input asp-for="@Model.AllIngredients[i].IngredientId" type="hidden" />
                        <input asp-for="@Model.AllIngredients[i].IngredientName" type="hidden" />
                    }
                    else
                    {
                        <input class="form-check-input" asp-for="@Model.AllIngredients[i].Selected" type="checkbox" id="defaultCheck1">
                        <label class="form-check-label" for="defaultCheck1">@Model.AllIngredients[i].IngredientName</label>
                        <input asp-for="@Model.AllIngredients[i].IngredientId" type="hidden" />
                        <input asp-for="@Model.AllIngredients[i].IngredientName" type="hidden" />
                    }
                </li>
            }
        </ul>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

<a asp-controller="Admin" asp-action="ManageIngredients">Manage ingredients</a>
@*<a asp-controller="Admin" asp-action="DeleteFood" asp-route-id="@Model.CurrentFood.FoodId">Delete</a>*@

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

Online-Shop/Views/Admin/Index.cshtml

<h1>Admin</h1>
<hr class="accent my-5">

<ul class="list-unstyled list-group list-group-flush">
    <li><a class="list-group-item" asp-controller="Admin" asp-action="ManageMenu"><i class="fas fa-pizza-slice"></i> Manage menu </a></li>
    <li><a class="list-group-item" asp-controller="Admin" asp-action="ManageIngredients"><i class="fas fa-apple-alt"></i> Manage ingredients </a></li>
    <li><a class="list-group-item" asp-controller="Admin" asp-action="ManageOrders"><i class="far fa-list-alt"></i> Manage orders </a></li>
    <li><a class="list-group-item" asp-controller="Admin" asp-action="ManageUsers"><i class="fas fa-users"></i> Manage users </a></li>
</ul>

Online-Shop/Views/Admin/ManageIngredients.cshtml
@model Online_Shop.ViewModels.ViewModelFood

<h1>Manage ingredients</h1>
<hr class="accent my-5">

<form asp-controller="Admin" asp-action="ManageIngredients" method="post">
    <div class="form-group">
        <input type="text" asp-for="CurrentIngredient.IngredientName" class="form-control" id="inputName4" placeholder="Name">
        <button class="btn btn-primary" type="submit"><i class="fas fa-plus"></i> Add</button>
        <span asp-validation-for="CurrentIngredient.IngredientName" style="color: red;"></span>
    </div>
</form>

<table>
    @foreach (var item in Model.AllIngredients)
    {
        <tr>
            <td>
                <form asp-controller="Admin" asp-action="EditIngredient" method="post">
                    <input type="text" asp-for="@Model.CurrentIngredient.IngredientName" value="@item.IngredientName" />
                    <input type="hidden" asp-for="@Model.CurrentIngredient.IngredientId" value="@item.IngredientId" />
                    <input class="btn btn-primary btn-sm" type="submit" value="Save" />
                </form>
            </td>
            @*<td>
                <a asp-controller="Admin" asp-action="RemoveIngredient" asp-route-id="@item.IngredientId">Delete</a>
            </td>*@
        </tr>
    }
</table>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.4.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

Online-Shop/Views/Admin/ManageMenu.cshtml
@model Online_Shop.ViewModels.ViewModelFood

<h1>Manage menu</h1>
<hr class="accent my-5">

<a class="btn btn-primary" asp-controller="Admin" asp-action="AddFood"><i class="fas fa-plus"></i> Add new food</a><br />
<table class="table table-striped">
    @foreach (var item in Model.AllFoods.OrderBy(f => f.Name))
    {
        <tr>
            <td>@item.Name</td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <ul class="ingredients" style="padding: 0">
                    @foreach (var ing in item.Ingredients)
                    {
                        <li>
                            @ing.IngredientName
                        </li>

                    }

                </ul>
            </td>
            <td>
                @item.Price
            </td>
            <td>
                <a asp-controller="Admin" asp-action="EditMenu" asp-route-id="@item.FoodId"><i class="fas fa-pencil-alt"></i></a>
            </td>
        </tr>
    }
</table>
<a class="btn btn-primary" asp-controller="Admin" asp-action="AddFood"><i class="fas fa-plus"></i> Add new food</a>

Online-Shop/Views/Admin/ManageOrders.cshtml

@model Online_Shop.ViewModels.ViewModelFood

<h1>Manage orders</h1>
<hr class="accent my-5">

<table class="table">
    <tr>
        <th>
            Order ID
        </th>
        <th>
            Date
        </th>
        <th>
            Total
        </th>
        <th>
            Delivered
        </th>
        <th>
            User
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model.AllOrders.OrderByDescending(o => o.OrderDate))
    {
        <tr>
            <td>
                @item.OrderId
            </td>
            <td>
                @item.OrderDate
            </td>
            <td>
                @item.TotalAmount
            </td>
            <td align="center">
                <form asp-controller="Admin" asp-action="ChangeOrderState" method="post">
                    <input asp-for="@Model.CurrentOrder.OrderId" value="@item.OrderId" type="hidden" />
                    <input asp-for="@Model.CurrentOrder.TotalAmount" value="@item.TotalAmount" type="hidden" />
                    <input asp-for="@Model.CurrentOrder.OrderDate" value="@item.OrderDate" type="hidden" />
                    <input asp-for="@Model.CurrentOrder.CustomerId" value="@item.CustomerId" type="hidden" />
                    @if (item.Delivered)
                    {
                        <input class="form-check-input" asp-for="@Model.CurrentOrder.Delivered"
                               onchange="this.form.submit()"
                               type="checkbox" id="defaultCheck1" checked>
                    }
                    else
                    {
                        <input class="form-check-input" asp-for="@Model.CurrentOrder.Delivered"
                               onchange="this.form.submit()"
                               type="checkbox" id="defaultCheck1">
                    }

                </form>

            </td>
            <td>
                @item.Customer.Username
            </td>
            <td>
                <a asp-controller="Admin" asp-action="RemoveOrder" asp-route-id="@item.OrderId"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
    }
</table>

Online-Shop/Views/Admin/ManageUsers.cshtml


@using Microsoft.AspNetCore.Identity
@using Online_Shop.ModelsIdentity

@model Online_Shop.ViewModels.ViewModelFood

<h1>Manage users</h1>
<hr class="accent my-5">

<table class="table">
    <tr>
        <th>
            Username
        </th>
        <th style="text-align: center">
            Premium
        </th>
        <th style="text-align: center">
            Admin
        </th>
    </tr>

    @foreach (var item in Model.AllUsers)
    {
        <tr>
            <td>
                @item.UserName
            </td>
            <td align="center">
                <form asp-controller="Admin" asp-action="ChangeMembership" method="post">
                    <input asp-for="@Model.CurrentUser.Id" value="@item.Id" type="hidden" />

                    @if (item.isPremium)
                    {
                        <input class="form-check-input" asp-for="@Model.CurrentUser.isPremium"
                               onchange="this.form.submit()"
                               type="checkbox" id="defaultCheck1" checked>
                    }
                    else
                    {
                        <input class="form-check-input" asp-for="@Model.CurrentUser.isPremium"
                               onchange="this.form.submit()"
                               type="checkbox" id="defaultCheck1">
                    }

                </form>

            </td>
            <td align="center">
                <form asp-controller="Admin" asp-action="ChangeAdmin" method="post">
                    <input asp-for="@Model.CurrentUser.Id" value="@item.Id" type="hidden" />

                    @if (item.isAdmin)
                    {
                        <input class="form-check-input" asp-for="@Model.CurrentUser.isAdmin"
                               onchange="this.form.submit()"
                               type="checkbox" id="defaultCheck1" checked>
                    }
                    else
                    {
                        <input class="form-check-input" asp-for="@Model.CurrentUser.isAdmin"
                               onchange="this.form.submit()"
                               type="checkbox" id="defaultCheck1">
                    }

                </form>

            </td>

        </tr>
    }
</table>